[package]
name = "womscp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
womscp-lib = { git = "https://github.com/W-Orchid/womscp-lib.git" }
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite"] }
