#+title: WOMSCP Server

This is an async server implementation of the [[https://github.com/W-Orchid/womscp-lib][WOMSCP]]. It uses sqlite as a database. The configuration can be set in the *config.toml* file.

* Requirements
- Cargo
- Sqlite


* Build and Run
#+begin_src shell
  cargo build --release
#+end_src

** Initializing
:properties:
:id: initializing
:end:
If you are running for the first time:
#+begin_src shell
  ./build/target/womscp-server init
#+end_src

** Running
If you already setup the server and want to just start it:
#+begin_src shell
  ./build/target/womscp-server
#+end_src

** Resetting Database
To reset the database just delete your database file (*w_orchid.db* by default) and go through the [[id:initializing][Initialization]] process again.

* Configuring and Usage
You can configure the following options from the *config.toml* file:
- *address*                       - the listening address of the server
- *database*                      - the database file path
- *microcontroller_count*         - the total number of microcontrollers in your system
- *sensors_per_microcontroller*   - the maximum number of sensors per microcontroller in your system


Some options can be set through the command-line when starting the server, see the help menu for more information.
#+begin_src shell
  ./target/release/womscp-server --help
#+end_src

* Benchmarking
You can find the benchmark program for this server [[https://github.com/W-Orchid/womscp-benchmark][here]].
